language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
  - mysql -uroot -e 'create database minecity_test;'
  - mysql -uroot -e "create user 'unit_test'@'localhost' identified by 'unit_test';"
  - mysql -uroot -e "grant all privileges on minecity_test.* to 'unit_test'@'localhost'"
  - mysql -uroot -e "flush privileges;"